#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6  

setxkbmap -option "grp:alt_shift_toggle" us,th


bspc config border_width         2
bspc config window_gap           1
bspc config normal_border_color "#707070"
bspc config focused_border_color "#3e8fb0"
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a vesktop floating=on
bspc rule -a captrine floating=on
bspc rule -a spotify floating=on
bspc rule -a dolphin floating=on

# bspc config initial_polarity first_child
# bspc config automatic_scheme longest_side

# This runs the script created by feh to restore the last wallpaper
sh ~/.fehbg &
$HOME/.config/polybar/launch.sh &
dunst &
greenclip daemon &
pgrep -x picom > /dev/null || picom &
sleep 0.2 &
